name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Regular
            dockerfile: Dockerfile
            suffix: ""
          - name: Alpine
            dockerfile: Dockerfile.alpine
            suffix: "-alpine"
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: joinflux/firebase-action
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=sha

      - name: Build ${{ matrix.name }} Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          build-args: |
            FIREBASE_VERSION='15.4.0'
          push: false
          tags: joinflux/firebase-action:test${{ matrix.suffix }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test ${{ matrix.name }} Docker image
        run: |
          docker run --rm joinflux/firebase-action:test${{ matrix.suffix }} --version
